library(base, quietly = TRUE)
library(methods, quietly = TRUE)
library(datasets, quietly = TRUE)
library(utils, quietly = TRUE)
library(grDevices, quietly = TRUE)
library(graphics, quietly = TRUE)
library(stats, quietly = TRUE)
library(gtools, quietly = TRUE)
library(sp, quietly = TRUE)
library(Matrix, quietly = TRUE)
library(spdep, quietly = TRUE)
library(rgdal, quietly = TRUE)
library(gdata, quietly = TRUE)
library(raster, quietly = TRUE)
library(lattice, quietly = TRUE)
library(RColorBrewer, quietly = TRUE)
library(latticeExtra, quietly = TRUE)
library(rasterVis, quietly = TRUE)
library(parallel, quietly = TRUE)
library(maptools, quietly = TRUE)
library(maps, quietly = TRUE)
library(plyr, quietly = TRUE)
library(spgwr, quietly = TRUE)
library(rgeos, quietly = TRUE)
library(gridExtra, quietly = TRUE)
library(colorRamps, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(forecast, quietly = TRUE)
library(multitaper, quietly = TRUE)
library(zoo, quietly = TRUE)
library(xts, quietly = TRUE)
library(mblm, quietly = TRUE)
library(leaps, quietly = TRUE)
library(locfit, quietly = TRUE)
library(nlme, quietly = TRUE)
library(mgcv, quietly = TRUE)
library(tseries, quietly = TRUE)
library(TSA, quietly = TRUE)
library(Rwave, quietly = TRUE)
library(pracma, quietly = TRUE)
library(seewave, quietly = TRUE)
library(rslurm, quietly = TRUE)
.rslurm_func <- readRDS('f.RDS')
.rslurm_params <- readRDS('params.RDS')
.rslurm_id <- as.numeric(Sys.getenv('SLURM_ARRAY_TASK_ID'))
.rslurm_istart <- .rslurm_id * 334 + 1
.rslurm_iend <- min((.rslurm_id + 1) * 334, nrow(.rslurm_params))
.rslurm_result <- do.call(parallel::mcmapply, c(
    FUN = .rslurm_func,
    .rslurm_params[.rslurm_istart:.rslurm_iend, , drop = FALSE],
    mc.cores = 2,
    SIMPLIFY = FALSE))

saveRDS(.rslurm_result, file = paste0('results_', .rslurm_id, '.RDS'))
