####################################    Using rslurm example   #######################################
##################################     RESEARCH SUPPORT SESYNC   #######################################
#This script experiment with the rslurm package and explores its various options.
#
#AUTHORS: Benoit Parmentier                                             
#DATE CREATED: 01/22/2017 
#DATE MODIFIED: 01/24/2017
#Version: 1
#PROJECT: PEATBOGS SESYNC
#TO DO:
#
#COMMIT: cleaning up rslurm tutorial script 
#
#################################################################################################

###Loading R library and packages                                                      

library(parallel)
library(rslurm)

##### Functions used in this script 

create_dir_fun <- function(out_dir,out_suffix){
  #if out_suffix is not null then append out_suffix string
  if(!is.null(out_suffix)){
    out_name <- paste("output_",out_suffix,sep="")
    out_dir <- file.path(out_dir,out_name)
  }
  #create if does not exists
  if(!file.exists(out_dir)){
    dir.create(out_dir)
  }
  return(out_dir)
}

load_obj <- function(f){
  env <- new.env()
  nm <- load(f, env)[1]
  env[[nm]]
}

#####  Parameters and argument set up ###########

#ARGS 1: input data directory
in_dir <- "/nfs/bparmentier-data/Data/SLURM_test/rslurm_test/data"
#ARGS 2: output dir
out_dir <- "/nfs/bparmentier-data/Data/SLURM_test/rslurm_test/outputs"
#ARGS 3: output suffix
out_suffix <-"rslurm_test_01242018" #output suffix for the files and ouptu folder #PARAM 8
#ARGS 4: generate child output dir?
create_out_dir_param=TRUE #PARAM9
#ARGS 4: number of cores to use in function
num_cores <- 2 # set to two for now

################# START SCRIPT ###############################

## First create an output directory

if(is.null(out_dir)){
  out_dir <- dirname(in_dir) #output will be created in the input dir
}

out_suffix_s <- out_suffix #can modify name of output suffix
if(create_out_dir_param==TRUE){
  out_dir <- create_dir_fun(out_dir,out_suffix_s)
  setwd(out_dir)
}else{
  setwd(out_dir) #use previoulsy defined directory
}


#### READ OR CREATE DATA INPUT:

# Create a data frame of mean/sd values for normal distributions
pars <- data.frame(par_m = seq(-10, 10, length.out = 1000),
                   par_sd = seq(0.1, 10, length.out = 1000))


#### SOURCE OR CREATE FUNCTION TO RUN for the SLURM job:
# Create a function to parallelize
ftest <- function(par_m, par_sd) {
  samp <- rnorm(10^7, par_m, par_sd)
  c(s_m = mean(samp), s_sd = sd(samp))
}


#### PART 1: SLURM RUN WIHTOUT OPTIONS

## Example:
ftest(pars[1,1],pars[1,2])

sjob1 <- slurm_call(f=ftest, #function to run
                    params=pars) #input parameters as data.frame, function is run on each row
print_job_status(sjob1)
#Show jobname (number generated automatically if nothing provided)
sjob1$jobname

## Access output: for each job a new directory is created in the current dir

#the dir contains the .sh,.R and data (.RDS) generated by the package to run a SLURM job
#The output can be access using:
rslurm_output_dir <- paste0("_rslurm_",sjob1$jobname)
list.files(path=rslurm_output_dir)

res <- get_slurm_out(sjob1) #this return the outputs recombined as data.frame
all.equal(pars, res) # Confirm correct output

## Print and check the *.sh generated
system(paste("cat",file.path(rslurm_output_dir,"submit.sh")))

#cat submit.sh
#!/bin/bash
#
#SBATCH --ntasks=1
#SBATCH --job-name=1dcf50817384
#SBATCH --output=slurm_0.out
#/usr/lib/R/bin/Rscript --vanilla slurm_run.R

## Remove the automatically generated script
cleanup_files(sjob1) #remove everything

#### PART 2: SLURM RUN WITH OPTIONS AND USING ARRAY JOB

## To run multiple job over multiple nodes with different inputs (i.e. array job) use slurm_apply

sjob2 <- slurm_apply(ftest, pars,jobname="slurm_test2")
print_job_status(sjob2)
res <- get_slurm_out(sjob2, "table") #this return the outputs recombined as data.frame
res #print results

### To use more options, we need to create a list with slurm options:
options_list = list("sesyncshared",             # partition (equivalent to queue) to submit job
                    "ALL",                      # mail-type: Mail events (NONE, BEGIN, END, FAIL, ALL)
                    "bparmentier@sesync.org",   # mail-user: where to send email
                    "00:25:00",                 # Time limit hrs:min:sec, also called wall time
                    "console_%A_%a.out", # console output
                    "log_%A_%a.err") # error log
                    
##Now assign options name for slurm job
names(options_list) <- c("partition",
                         "mail-type",
                         "mail-user",
                         "time",
                         "output",
                         "error")

### Now submit job with full information
sjob3 <- slurm_apply(f=ftest, 
                      params=pars, 
                      jobname = "slurm_test3", 
                      nodes = 3, 
                      cpus_per_node = 2,
                      add_objects = NULL, 
                      pkgs = rev(.packages()), 
                      libPaths = NULL,
                      slurm_options = options_list, #use the slurm options set above
                      submit = TRUE)

#chek in Terminal in RStudio using squeue
#bparmentier@sshgw02:/nfs/bparmentier-data/Data/SLURM_test/rslurm_test/outputs/output_rslurm_test_01222018$ squeue
#JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
#294001_0 sesyncsha parallel bparment  R       0:08      1 pn33
#294001_1 sesyncsha parallel bparment  R       0:08      1 pn34
#294001_2 sesyncsha parallel bparment  R       0:08      1 pn35

#the dir contains the .sh,.R and data (.RDS) generated by the package to run a SLURM job
#The output can be access using:
rslurm_output_dir <- paste0("_rslurm_",sjob3$jobname)
list.files(path=rslurm_output_dir) #note we have three *.out files and *.err files

res <- get_slurm_out(sjob3, "table") #this return the outputs recombined as data.frame
all.equal(pars, res) # Confirm correct output
res

## Print and check the *.sh generated
system(paste("cat",file.path(rslurm_output_dir,"submit.sh")))

##Note the keyword option "--array=0-2" that is used to launch three jobs on different nodes.

################################# END OF SCRIPT #################################